name: CI

on:
  push:
  pull_request:

jobs:
  run-s3-script:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: Rscript -e 'install.packages(c("paws", "aws.s3"))'

      - name: Check environment variables
        run: |
          echo "Checking environment variables..."
          echo "MY_API_KEY is set? ${{ env.ACCESS_KEY_ID != '' }}"
          echo "SECRET_ACCESS_KEY is set? ${{ env.SECRET_ACCESS_KEY != '' }}"

      - name: Load credentials
        run: Rscript R/load_credentials.R
